This notebook shows the classification result (including Table 2 and Fig S1) in

    <Deriving information from missing data: implications for mood prediction>

In [1]:
import os

import random
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import csv

import matplotlib.dates as mdates
import h5py


import copy
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
import iisignature
from datetime import date


random.seed(42)
from data_cleaning import *
from classifiers import *
from data_transforms import *

Load ALTAN/QIDS data in AMoSS dataset

In [3]:
test_path='./all-true-colours-matlab-2017-02-27-18-38-12-nick/'
participants_list, participants_data_list,\
        participants_time_list=loadParticipants(test_path)
Participants=make_classes(participants_data_list,participants_time_list,participants_list)
cohort=cleaning_sameweek_data(cleaning_same_data(Participants))

14050


run the following three models in one function:
    
    * missing-response-incorporated signature-based classification model (MRSCM, level2)
    * missing-response-incorporated signature-based classification model (MRSCM, level3)
    * naive classification model 

In [4]:
if __name__ == "__main__":


    CM, mean_accuracy, accuracy_vectors=model_onego(cohort, 20,\
                                                    training=0.7,\
                                                    sample_size=100)

In [13]:
print("For naive classification model:")
print("the mean accuracy is",mean_accuracy[0])
print("the confusion matrix is:\n ",CM[0])

For naive classification model:
the mean accuracy is 0.5607894736842108
the confusion matrix is:
  [[ 382.  204.  417.]
 [  47. 1021.  292.]
 [ 213.  496.  728.]]


In [14]:
print("For MRSCM, level2:")
print("the mean accuracy is",mean_accuracy[1])
print("the confusion matrix is:\n ",CM[1])

For MRSCM, level2:
the mean accuracy is 0.6568421052631578
the confusion matrix is:
  [[ 558.  116.  329.]
 [  19. 1089.  252.]
 [ 255.  333.  849.]]


Corresponding f1 scores can be computed based on above confusion matrices.